// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package recipes_db

import (
	"time"
)

type Recipe struct {
	ID           int32     `json:"id"`
	Title        string    `json:"title"`
	Description  string    `json:"description"`
	CookingTime  string    `json:"cookingTime"`
	Ingredients  []string  `json:"ingredients"`
	Instructions string    `json:"instructions"`
	DateCreated  time.Time `json:"dateCreated"`
}
