// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package recipes_db

import (
	"context"
)

type Querier interface {
	CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error)
	DeleteRecipe(ctx context.Context, id int32) error
	GetRecipe(ctx context.Context, id int32) (Recipe, error)
	ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error)
	UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error)
}

var _ Querier = (*Queries)(nil)
