// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: recipe.sql

package recipes_db

import (
	"context"
	"database/sql"
	"time"

	"github.com/lib/pq"
)

const CreateRecipe = `-- name: CreateRecipe :one
INSERT INTO recipes (
  title,
  description,
  cooking_time,
  ingredients,
  instructions,
  date_created
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, title, description, cooking_time, ingredients, instructions, date_created
`

type CreateRecipeParams struct {
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CookingTime  string         `json:"cookingTime"`
	Ingredients  []string       `json:"ingredients"`
	Instructions string         `json:"instructions"`
	DateCreated  time.Time      `json:"dateCreated"`
}

func (q *Queries) CreateRecipe(ctx context.Context, arg CreateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, CreateRecipe,
		arg.Title,
		arg.Description,
		arg.CookingTime,
		pq.Array(arg.Ingredients),
		arg.Instructions,
		arg.DateCreated,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CookingTime,
		pq.Array(&i.Ingredients),
		&i.Instructions,
		&i.DateCreated,
	)
	return i, err
}

const DeleteRecipe = `-- name: DeleteRecipe :exec
DELETE FROM recipes
WHERE id = $1
`

func (q *Queries) DeleteRecipe(ctx context.Context, id int32) error {
	_, err := q.db.ExecContext(ctx, DeleteRecipe, id)
	return err
}

const GetRecipe = `-- name: GetRecipe :one
  SELECT id, title, description, cooking_time, ingredients, instructions, date_created FROM recipes
  WHERE id = $1 LIMIT 1
`

func (q *Queries) GetRecipe(ctx context.Context, id int32) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, GetRecipe, id)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CookingTime,
		pq.Array(&i.Ingredients),
		&i.Instructions,
		&i.DateCreated,
	)
	return i, err
}

const ListRecipes = `-- name: ListRecipes :many
SELECT id, title, description, cooking_time, ingredients, instructions, date_created FROM recipes
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListRecipesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListRecipes(ctx context.Context, arg ListRecipesParams) ([]Recipe, error) {
	rows, err := q.db.QueryContext(ctx, ListRecipes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Recipe{}
	for rows.Next() {
		var i Recipe
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.CookingTime,
			pq.Array(&i.Ingredients),
			&i.Instructions,
			&i.DateCreated,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateRecipe = `-- name: UpdateRecipe :one
UPDATE recipes
  set title = $2,
  description = $3,
  cooking_time = $4,
  ingredients = $5,
  instructions = $6
WHERE id = $1
RETURNING id, title, description, cooking_time, ingredients, instructions, date_created
`

type UpdateRecipeParams struct {
	ID           int32          `json:"id"`
	Title        string         `json:"title"`
	Description  sql.NullString `json:"description"`
	CookingTime  string         `json:"cookingTime"`
	Ingredients  []string       `json:"ingredients"`
	Instructions string         `json:"instructions"`
}

func (q *Queries) UpdateRecipe(ctx context.Context, arg UpdateRecipeParams) (Recipe, error) {
	row := q.db.QueryRowContext(ctx, UpdateRecipe,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.CookingTime,
		pq.Array(arg.Ingredients),
		arg.Instructions,
	)
	var i Recipe
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.CookingTime,
		pq.Array(&i.Ingredients),
		&i.Instructions,
		&i.DateCreated,
	)
	return i, err
}
