services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=recipes_db
    ports:
    - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgresql://root:mysecretpassword@postgres:5432/recipes_db?sslmode=disable
    depends_on:
      - postgres
    entrypoint: [ "/app/wait-for.sh", "postgres:5432", "--", "/app/start.sh" ]
    command: [ "/app/main" ]
  front:
    build:
      context: ./front
      dockerfile: ./front/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - app
    image: front:react
    container_name: react_container
    command: npm start
